name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.20.1'

    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm cache clean --force && npm install --legacy-peer-deps
    - run: npm install -g @angular/cli@6.1.1 > /dev/null
    - run: ng build --prod

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Sync Files to Server
      run: |
        rsync -av --exclude='.htaccess' -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' $GITHUB_WORKSPACE/dist/UTS/ ${{ secrets.FTP_USERNAME }}@${{ secrets.KNOWN_HOSTS }}:/var/www/html/
